# Generated by Django 5.1.1 on 2025-03-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('season', models.CharField(max_length=6)),
                ('games_played', models.IntegerField(blank=True, default='', null=True)),
                ('points_per_game', models.FloatField(blank=True, default='', null=True)),
                ('assists_per_game', models.FloatField(blank=True, default='', null=True)),
                ('rebounds_per_game', models.FloatField(blank=True, default='', null=True)),
            ],
            options={
                'unique_together': {('player_name', 'season')},
            },
        ),
        migrations.CreateModel(
            name='TeamStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('season', models.CharField(max_length=6)),
                ('games_played', models.IntegerField(blank=True, default='', null=True)),
                ('points_per_game', models.FloatField(blank=True, default='', null=True)),
                ('assists_per_game', models.FloatField(blank=True, default='', null=True)),
                ('rebounds_per_game', models.FloatField(blank=True, default='', null=True)),
            ],
            options={
                'unique_together': {('team_name', 'season')},
            },
        ),
    ]
